### ISSUE TITLE
How to open the java file?

### ISSUE THREAD

**Issue by eyemiru** [edjacob25/WhatsApp-Analyzer#1]
On windows:

Installed Java 8
Have jfreechart 1.0.19

How to open the file? Do you still support it?

Thanks
eyemiru

**Comment by edjacob25** [comment]
Hi! I'm sorry, I took this long to respond.  If I recall correctly, you have to open the project in Intellij Idea and then add the jars of JFreeChart and JavaFx, then making a Intellij Idea build config of FX and launching it. If you give me some time, I can make a maven build script. 

I ported most of the project to an Android app, which I do not have up here, but has better performance overall.

**Comment by edjacob25** [comment]
Hi @eyemiru, I've uploaded the Android version here https://github.com/edjacob25/Whatsapp-Analyzer-Android so you can check it out.
